[package]
name = "formatted_debug"
version = "0.1.0"
edition = "2021"
description = "A small library which provides help with basic formatting"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
